hyesungoh/comet-land

apps/blog/jest.setup.js
apps/blog/next-env.d.ts
apps/blog/src/hooks/useInfiniteScroll.test.ts
apps/blog/src/hooks/useInfiniteScroll.ts
apps/blog/src/pages/category/[category].tsx
apps/blog/src/pages/index.tsx
apps/resume/jest.setup.js
apps/resume/next-env.d.ts
apps/resume/src/components/ContactButton/ContactButton.test.tsx
jest.setup.js
packages/config/jest-setup.js
packages/config/jest.js
packages/config/package.json
packages/core/jest.setup.js
packages/tsconfig/config-nextjs.json

```tsx
// index.tsx
useInfiniteScroll({sessionKey: "home", ...})
```
```tsx
// index.tsx
useInfiniteScroll({...}) // there is no key
// useInfiniteScroll.ts
const sessionKey = useMemo(() => `isv-${router.asPath}`, [router]);
```
reduce human mistake possibility

handling infinite scroll session key at hooks

---

apps/blog/public/rss.xml
apps/blog/scripts/generate-static-files.mjs
apps/blog/src/constants/KbarActions/index.ts

apply rss feed at `${blogUrl}/rss.xml`.
with auto generate when predev and prebuild

Apply RSS feed at blog

---

apps/blog/_config/index.json
apps/blog/_config/index.ts
apps/blog/src/constants/KbarActions/index.ts
apps/resume/src/constants/KbarActions/KbarActions.ts
packages/core/components/Icon/svg/Info.tsx
packages/core/components/Icon/svg/index.tsx

- not showing email and blog url data at resume
- doesn't have link for blog to resume
- showing email and blog url data
- append kbar action for blog to resume

Update two app's relationship with link

---

apps/resume/src/components/ContactButton/ContactButton.test.tsx
apps/resume/src/components/ContactButton/index.test.tsx
apps/resume/src/components/Header/Header.test.tsx
apps/resume/src/components/Header/index.test.tsx
apps/resume/src/components/Li/Li.test.tsx
apps/resume/src/components/Li/index.test.tsx
apps/resume/src/components/OtherExperienceSection/Experience.test.tsx
apps/resume/src/components/OtherExperienceSection/Experience.tsx
apps/resume/src/components/OtherExperienceSection/OtherExperienceSection.test.tsx
apps/resume/src/components/OtherExperienceSection/OtherExperienceSection.tsx
apps/resume/src/components/OtherExperienceSection/index.test.tsx
apps/resume/src/components/Section/Section.test.tsx
apps/resume/src/components/Section/index.test.tsx
apps/resume/src/components/SkillsSection/Skill.test.tsx
apps/resume/src/components/SkillsSection/Skill.tsx
apps/resume/src/components/SkillsSection/SkillsSection.test.tsx
apps/resume/src/components/SkillsSection/SkillsSection.tsx
apps/resume/src/components/SkillsSection/index.test.tsx
apps/resume/src/components/TitleTooltip/TitleTooltip.test.tsx
apps/resume/src/components/TitleTooltip/index.test.tsx

Apply test code at Resume app's ...
- TitleTooltip
- SkillsSection
- Section
- OtherExperienceSection
- Experience
- ContactButton
- Header
- Li

Apply test at Resume components

---

apps/resume/src/components/WorkExperienceSection/Project.tsx

apply `transition` attr at `TechSpan`
closed #57

resume app's tech span can be animated

---

packages/core/components/ThemeSwitch/ThemeSwitch.tsx

* fixing #61 with override color of `ThemeSwitch` component
closed #61

ThemeSwitch hover color override

---

README.md
apps/blog/_content/Guide/how-to-start.md

- update readme (use case, using create comet land)
- update post 'how-to-start'

Add use case and create comet land to readme

---

packages/core/components/PageProgressBar/PageProgressBar.tsx

fixing #55 
with `ResizeObserver` at document.body
> remain window resize event for window height change

Detect body resize with ResizeObserver at PageProgressBar

---

apps/blog/src/components/DateAndCategoryLink/DateAndCategoryLink.test.tsx
apps/blog/src/components/DateAndCategoryLink/DateAndCategoryLink.tsx
apps/blog/src/components/DateAndCategoryLink/index.test.tsx

apply more test at `blog/components/DateAndCategory` component

Apply test at blog/DateAndCategoryLink component

---

README.md
_docs/ko-readme.md

update korean readme for `create-comet-land` and `use cases`

korean readme update

---

apps/blog/src/components/AuthorSection/AuthorSection.test.tsx
apps/blog/src/components/AuthorSection/AuthorSection.tsx
apps/blog/src/components/AuthorSection/index.test.tsx
packages/core/components/Kbar/KBarToggleButton.tsx

apply test code at `blog/components/AuthorSection`

apply test at blog - author section component

---

packages/core/constants/General/index.ts

fix typo at Core General commnet

---

apps/blog/src/components/SEO/SEO.test.tsx
apps/blog/src/components/SEO/index.test.tsx

apply test code at `blog/components/SEO`

Test at blog SEO component

---

apps/blog/src/components/Comments/Comments.test.tsx
apps/blog/src/components/Comments/Comments.tsx
apps/blog/src/components/Comments/index.test.tsx

- Apply test code at `blog/components/Comments`

Test at blog comments component

---

apps/blog/src/utils/getHeadings.test.tsx

- Apply test code at `blog/utils/getHeadings`

Test at blog getHeadings utils

---

apps/blog/src/components/TOC/TOC.test.tsx
apps/blog/src/components/TOC/TOC.tsx
apps/blog/src/components/TOC/index.test.tsx

- apply test code at `blog/components/TOC`

Test blog TOC index, mocking TOC useState

---

README.md
_docs/ko-readme.md
apps/blog/_content/Guide/how-to-start.md

- apply manual guide of `deploy with vercel`
- updated korean readme

Update readme for deploy

---

apps/blog/src/libs/api/api.test.ts
apps/blog/src/libs/api/api.ts
apps/blog/src/libs/api/index.test.ts

- apply test code at `blog/libs/api`

Apply test at blog markdown api

---

apps/blog/src/libs/api/api.ts
apps/blog/src/pages/[slug].page.tsx
apps/blog/src/pages/__test__/404.test.tsx
apps/blog/src/pages/__test__/500.test.tsx
apps/blog/src/pages/__test__/[slug].test.tsx
apps/blog/src/pages/__test__/_app.test.tsx
apps/blog/src/pages/__test__/_document.test.tsx
apps/blog/src/pages/__test__/_offline.test.tsx
apps/blog/src/pages/__test__/category/[category].test.tsx
apps/blog/src/pages/__test__/index.test.tsx

- Apply test code ab `blog/pages`

Apply test at blog pages

---

apps/blog/cypress.config.ts
apps/blog/cypress/config/index.ts
apps/blog/cypress/e2e/main.spec.ts
apps/blog/cypress/tsconfig.json
apps/blog/package.json
apps/resume/_content/Header/index.ts
apps/resume/cypress.config.ts
apps/resume/cypress/config/index.ts
apps/resume/cypress/e2e/main.spec.ts
apps/resume/cypress/tsconfig.json
apps/resume/package.json
packages/config/eslint-nextjs.js
packages/config/package.json
packages/tsconfig/config-cypress.json
yarn.lock

- delete overlaped dependencies
- replace e2e config files to `cypress.config.ts`
- generate cypress tsconfig at `packages/tsconfig`

update cypress configuration (ts, cypress.config, deps)

---

.github/CODEOWNERS
apps/blog/public/sitemap.xml

- setting code owners at `.github`
- update blog sitemap following #90

setting code owners

---

apps/blog/cypress/e2e/main.spec.ts
apps/blog/cypress/e2e/root/header.spec.ts

- apply test code at blog app's root route - header

E2E test at blog root route's header

---

apps/resume/cypress/e2e/main.spec.ts
apps/resume/cypress/e2e/root/header.spec.ts

- apply test code at `resume/header`

Apply e2e test at resume header

---

apps/resume/cypress/e2e/root/header.spec.ts

- apply test code about theme toggle switch at `resume/header`

Apply theme toggle switch e2e test at resume

---

apps/blog/cypress/e2e/root/main.spec.ts

- Apply e2e test at `blog`'s `root/main`

Apply e2e test at blog root main

---

apps/blog/cypress/e2e/root/footer.spec.tsx
apps/blog/cypress/tsconfig.json
apps/resume/cypress/tsconfig.json
packages/tsconfig/config-cypress.json

- replace package's cypress configuration's `include` option to each cypress tsconfig
- apply e2e test code at `blog`'s `footer`

Apply e2e test at blog footer

---

apps/blog/cypress.config.ts
apps/blog/cypress/e2e/slug/main-and-aside.spec.ts

- apply e2e test code at blog slug page's `main`
- apply e2e test code at blog slug page's `aside`
- set cypress command timeout to `30000`

Apply e2e test at blog slug main and aside

---

apps/blog/src/pages/[slug].page.tsx

- apeend margin `3rem` at author section of slug

Append margin at author section of slug

---

packages/core/constants/Colors/index.ts
packages/core/styles/theme/darkTheme.ts
packages/core/styles/theme/lightTheme.ts

- apply configurable `lightBackground`, `darkBackground` color
- `primaryShadow` following primary color when light theme

Apply configurable background color

---

README.md

fix: modify use case url.

---

.github/labeler.yml
.github/workflows/labeler.yml

Apply [actions/labeler](https://github.com/actions/labeler)

Apply labeler at pull request

---

README.md

chore: add new use case

---

README.md

Append use case

---

packages/core/components/Footer/index.test.tsx
packages/core/components/Icon/Icon.test.tsx
packages/core/components/Icon/index.test.tsx

append test at..
- core/Footer/index
- core/Icon/index
- core/Icon/Icon

append few tests

---

_docs/ko-readme.md

update korean readme

---

apps/resume/src/components/TitleTooltip/TitleTooltip.tsx
packages/core/components/Kbar/Result.tsx
packages/core/components/Kbar/Search.tsx

update below element's color
- resume tooltip icon
- kbar input placeholder
- kbar elements text and icon

Update resume and kbar elements color

---

apps/resume/src/components/WorkExperienceSection/Company.tsx
apps/resume/src/components/WorkExperienceSection/WorkExperienceSection.tsx

append margin when mobile

---

apps/blog/src/components/SEO/SEO.tsx

delete useless type at SEO components

SEO props type

---

README.md

docs: append use case

---

README.md
_docs/ko-readme.md

좋은 프로젝트를 만들어 주셔서 감사합니다!
use case 추가입니다!

Update README about usecase
